# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import djongo.models
import dummy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('content', djongo.models.EmbeddedModelField(model_container=dummy.models.BlogContent, model_form=dummy.models.BlogContentForm)),
            ],
        ),
        migrations.CreateModel(
            name='Dummy2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleBlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('content', djongo.models.ArrayModelField(model_container=dummy.models.BlogContent, model_form=dummy.models.BlogContentForm)),
            ],
        ),
    ]
