source 'https://rubygems.org'

# gem stripe
# run locally
 gem 'github-pages', group: :jekyll_plugins
 gem "jekyll-include-cache"

# run server
 gem "minimal-mistakes-jekyll"
# gem "jekyll", "~> 3.5"
# gem 'wdm'
